import { writeFileSync } from 'node:fs';
import { buildPriorV2Model } from '../../src/ai/tensor/modelV2';

/**
 * Regenerate the committed Tensor v2 imitation prior.
 *
 * Run after changing the demonstrations, the context slots, or any phase intent
 * vocabulary — the artifact is indexed against all three, and a stale file
 * would have the runtime play the old lessons through the new alphabet.
 *
 *   npm run tensor2:prior
 */
const OUT = 'src/ai/tensor/modelV2Data.ts';

const model = buildPriorV2Model();
const body = `// AUTO-GENERATED by tools/selfplay/tensorV2Prior.ts — do not edit by hand.
// The Tensor v2 imitation prior: expert strategic demonstrations fitted into one
// conditional MPS per phase (see docs/tensor-retrain-plan.md and
// src/ai/tensor/modelV2.ts, which holds the demonstrations themselves).
import type { TensorV2Model } from './modelV2';

export const PRIOR_V2_MODEL: TensorV2Model = ${JSON.stringify(model)};
`;
writeFileSync(OUT, body);
console.log(`wrote ${OUT} (${body.length} bytes, vocab ${model.vocab})`);
