/**
 * Pure model I/O + imitation pretraining for the tensor spike — deliberately
 * free of any AIController/sim import so it can BOOTSTRAP the committed model
 * file (src/ai/tensor/model.ts) that AIController in turn imports. The self-play
 * trainer (tensor.ts) reuses these helpers.
 *
 * Run directly to (re)generate the imitation prior:
 *   tsx tools/selfplay/tensorModel.ts
 */
import { writeFileSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { Rng } from '../../src/engine/rng';
import { randomMPS, fitStep, serializeMPS, deserializeMPS, type MPS, type SerializedMPS } from '../../src/ai/tensor/mps';
import { ACTION_DIM, PLAN_LENGTH, BOND_DIM, expertPlans } from '../../src/ai/tensor/plan';

export const MODEL_PATH = resolve(process.cwd(), 'src/ai/tensor/model.ts');

/** Imitation prior: fit the MPS to the human expert openings so it samples a
 *  sensible spread out of the box, before any self-play. */
export function pretrain(): MPS {
  const mps = randomMPS(PLAN_LENGTH, ACTION_DIM, BOND_DIM, new Rng(20260720));
  const experts = expertPlans();
  for (let step = 0; step < 240; step++) fitStep(mps, experts, 0.08);
  return mps;
}

export function loadModel(): SerializedMPS {
  const src = readFileSync(MODEL_PATH, 'utf8');
  const match = src.match(/TENSOR_MODEL: SerializedMPS = (\{[\s\S]*?\});/);
  if (!match) throw new Error('could not parse model.ts');
  return JSON.parse(match[1]) as SerializedMPS;
}

export function loadModelMPS(): MPS { return deserializeMPS(loadModel()); }

export function writeModel(mps: MPS, meta: Record<string, unknown>): void {
  const s = serializeMPS(mps);
  const round = (n: number): number => Math.round(n * 1e6) / 1e6;
  const model: SerializedMPS = { L: s.L, d: s.d, bond: s.bond, cores: s.cores.map(c => c.map(round)) };
  const body = `// AUTO-GENERATED by tools/selfplay/tensorModel.ts — do not edit by hand.\n`
    + `// The committed Matrix Product State strategy generator (see docs/tensor-strategy-poc.md).\n`
    + `import type { SerializedMPS } from './mps';\n\n`
    + `export const TENSOR_MODEL: SerializedMPS = ${JSON.stringify(model)};\n\n`
    + `export const TENSOR_MODEL_META = ${JSON.stringify(meta, null, 2)} as const;\n`;
  writeFileSync(MODEL_PATH, body);
  process.stdout.write(`wrote ${MODEL_PATH}\n`);
}

// Direct run = (re)generate the imitation prior. Guarded so importing this
// module (from tensor.ts) never triggers a write.
if (process.argv[1] && /tensorModel\.ts$/.test(process.argv[1])) {
  process.stdout.write('imitation pretrain on expert openings…\n');
  writeModel(pretrain(), { generatedAt: new Date().toISOString(), method: 'imitation-pretrain', generations: 0 });
}
